// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQEG0UGTREcYpYgeTMxU935cQmv_evjA',
    appId: '1:835970401631:web:be37776d2391190a30e2ea',
    messagingSenderId: '835970401631',
    projectId: 'bible-ea478',
    authDomain: 'bible-ea478.firebaseapp.com',
    storageBucket: 'bible-ea478.firebasestorage.app',
    measurementId: 'G-1MG5QCL3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwG2j2FTuAON8SxX8Gs-SBKDGdX9JsR5w',
    appId: '1:835970401631:android:fa3a24f43d4c48c330e2ea',
    messagingSenderId: '835970401631',
    projectId: 'bible-ea478',
    storageBucket: 'bible-ea478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-Ad1lmy_f5P6wgcVVJ2guTbPQvVFFk0',
    appId: '1:835970401631:ios:61f7728e6cc6bba130e2ea',
    messagingSenderId: '835970401631',
    projectId: 'bible-ea478',
    storageBucket: 'bible-ea478.firebasestorage.app',
    iosBundleId: 'com.example.bible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-Ad1lmy_f5P6wgcVVJ2guTbPQvVFFk0',
    appId: '1:835970401631:ios:61f7728e6cc6bba130e2ea',
    messagingSenderId: '835970401631',
    projectId: 'bible-ea478',
    storageBucket: 'bible-ea478.firebasestorage.app',
    iosBundleId: 'com.example.bible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaQEG0UGTREcYpYgeTMxU935cQmv_evjA',
    appId: '1:835970401631:web:d7eecb24ed571b7030e2ea',
    messagingSenderId: '835970401631',
    projectId: 'bible-ea478',
    authDomain: 'bible-ea478.firebaseapp.com',
    storageBucket: 'bible-ea478.firebasestorage.app',
    measurementId: 'G-Y4CYTGNV4E',
  );
}
